projects:
  masseffect5e:
    schemaPath: ./graphql/schema.json
    includes:
      - ./graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: ./graphql
        maxDepth: 4
extensions:
  amplify:
    version: 3
