projects:
  masseffect5e:
    schemaPath: 'E:/Sites/mass-effect/masseffect-5e/graphql/schema.json'
    includes:
      - graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: graphql
